### ISSUE TITLE
How does the UID work?

### ISSUE THREAD

**Issue by forkoz** [talentraspel/GD-77#4]
I'm unable to post to the group because of some google error so hopefully I can ask here.

What is at 0x0007f800 in the original flash dumps? In your 3.1.1 the results produced by the tool differ than what is at that location. I have not compared my 3.1.8 because I'm not able to build the CPS to read the register.  

Is this to enable flashing with HW tools like jtag or to allow flashing generic full image wrapped by encryption?

**Comment by talentraspel** [comment]
The are two encoded versions of the CPU-UID stored at 0x0007f800. One for the bootloader CPU-UID checks and one for the several mainapp CPU-UID checks. It is normal that this area is diferent for each GD-77 as it depend on the CPU-UID.

**Comment by forkoz** [comment]
Ahh, ok, so its for sharing full flash. Perhaps you can do compiled CPS in the work folder so I can pull mine. I have sharp develop but it doesn't compile. I'd have to get visual studio it seems.

**Comment by talentraspel** [comment]
It is for beeing able to get a full flash up and running on another system that the original one. This will mostly be a development board.

Compiled CPS version with the readout patches are already in the folder. Please check again.

**Comment by talentraspel** [comment]
Please fork the repo instead of generating pull requests. I don't have the time to check and pull stuff everytime. If I find the time I'll may pull stuff into my repo but it is better if you have your data in your fork so I don't become gatekeeper.

BTW: I don't like the idea of going for IDA with HexRay decompiler or other commercial tools. It is better to (additionally) use open source tools like Radare2 and/or RetDec or at least convert the findings to their format. This way everybody can use the results.

I assume you have proper licence for the IDA version with which you generated the files. IDA with HexRay is not to be known as very cheap. Anyway please publish the results in your fork please.
